name: Compare Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  compare-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage (PR branch)
        run: npm test -- --coverage

      - name: Save coverage report (PR branch)
        run: cp coverage/lcov-report/index.html coverage-pr.html

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Install dependencies (main branch)
        run: npm ci

      - name: Run tests with coverage (main branch)
        run: npm test -- --coverage

      - name: Save coverage report (main branch)
        run: cp coverage/lcov-report/index.html coverage-main.html

      - name: Compare coverage with Node.js
        run: node scripts/compareCoverage.js

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: coverage-comment.txt
          github-token: ${{ secrets.GB_TOKEN }}
